### ISSUE TITLE
Contributing to the project

### ISSUE THREAD

**Issue by leandronsp** [kiqr/kiqr#30]
Hi, I've found this project is very interesting. How should we contribute to it? Could you please provide a CONTRIBUTING.md or may I start writing a guide on my own by submitting a PR?

Thanks

**Comment by kjellberg** [comment]
Hi @leandronsp! Nice to see you here and glad you want to join :) Even though I'm not really prepared for contributions yet, I'd appreciate all kinds of PR's and contributions - big and small. That would also motivate me to keep working on this project.

Can I ask you if you've tried KIQR and got it to work? 

Just to let you know that it's still in an early stage, I have some bigger breaking changes planned, for example refactoring this repo to only include the gem (https://github.com/kiqr/kiqr/tree/main/gems/kiqr) and extract all Rails code and views to a separated starter kit - #14.

**Comment by leandronsp** [comment]
Nice @kjellberg , I think I'll dig into some issues and see how could I contribute. As soon as I get some work done, I'm ready to submit a pull request.
